const conversor = require('./ModuloConversor')
console.log("---------------------NO-RECURSIVO-----------------")
conversor.convierte(1256,16)
console.log("---------------------RECURSIVO-----------------")
conversor.convierteR(1256,16)